source "https://rubygems.org"

ruby "2.5.1"

gem "bourbon", "~> 5.0"
gem "builder", "~> 3.2"
gem "middleman", "~> 4.2"
gem "middleman-aria_current", "~> 0.1"
gem "middleman-autoprefixer", "~> 2.9"
gem "middleman-blog"
gem "middleman-livereload", "~> 3.4"
gem "middleman-minify-html", "~> 3.4"
gem "middleman-syntax"
gem "neat", "~> 2.1"
gem "nokogiri"
gem "redcarpet", "~> 3.4"
gem "sass", "~> 3.4"
gem "slim"
